import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import ParticleJs from "@/components/Particle";
import Header from "@/components/Header";

const mont = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AI Zypher",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={mont.className}>
        <ParticleJs />
        <Header />
        {children}
      </body>
    </html>
  );
}
